[package]
org = "wso2"
name = "terminology_service_api"
version = "0.1.0"
distribution = "2201.10.2"
template=true

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "6.0.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.international401"
version = "3.0.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "6.0.2"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.validator"
version = "5.0.1"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.terminology"
version = "5.0.3"
repository = "local"

[[tool.persist]]
id = "generate-db-client"
targetModule = "terminology_service_api.store"
options.datastore = "mysql"
options.testDatastore = "h2"
filePath = "persist/model.bal"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.6.0"


